# REUSABLE WORKFLOW FOR: Backend Tests
# PURPOSE: Run backend tests when called by other workflows or manually triggered
# TESTS: Runs backend unit and integration tests isolated in a Docker container

name: Test Backend

on:
  # Allow this workflow to be called by other workflows and pass required secrets
  workflow_call:
    secrets:
      JWT_SECRET_KEY:
        description: "Secret key for JWT authentication"
        required: true
      OMDB_API_KEY:
        description: "API key for OMDB API for movie data"
        required: true

  # Allow manual triggering for testing this workflow independently
  workflow_dispatch:

jobs:
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      # Downloads repo code to runner
      - name: Checkout code
        uses: actions/checkout@v4

        # Setup Docker Buildx for building and running test containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Run backend tests in Docker container, passing the environment variables
      - name: Run Tests
        env:
          # MongoDB Database connection for tests
          DATABASE_URI: mongodb://mongodb:27017/movie_db_test

          # Secret keys passed to workflow (from stored secrets in GitHub Actions)
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}

          # Header key for API configuration
          TOKEN_HEADER_KEY: authorization

        # Run the backend tests using Docker Compose, ensuring it builds the image and exits with the correct code based on test results
        # npm test exits with 0 → command exits with 0 → step passes ✅
        # npm test exits with 1 → command exits with 1 → step fails ❌
        run: |
          docker compose -f docker-compose.test.yml up backend-test \
            --build \
            --abort-on-container-exit \
            --exit-code-from backend-test

        # Cleanup containers and volumes after tests run, regardless of test success or failure
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
