# REUSABLE WORKFLOW FOR: Backend Tests
# PURPOSE: Run backend tests when called by other workflows or manually triggered
# TESTS: Runs backend unit and integration tests isolated in a Docker container

name: Test Backend

on:
  # Allow this workflow to be called by other workflows and pass required secrets
  workflow_call:
    secrets:
      JWT_SECRET_KEY:
        description: "Secret key for JWT authentication"
        required: true
      OMDB_API_KEY:
        description: "API key for OMDB API for movie data"
        required: true
    outputs:
      result:
        description: "Outcome of the backend test job"
        value: ${{ jobs.test-backend.outputs.result }}

  # Allow manual triggering for testing this workflow independently
  workflow_dispatch:

jobs:
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    # This outputs the outcome of the tests results to the workflow
    outputs:
      result: ${{ steps.run-tests.outcome }}

    steps:
      # Downloads repo code to runner
      - name: Checkout code
        uses: actions/checkout@v4

        # Setup Docker Buildx for building and running test containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Run backend tests in Docker container, passing the environment variables
      - name: Run Backend Tests
        # This step is used to store the outcome of the tests in a variable
        id: run-tests
        env:
          NODE_ENV: test
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          TOKEN_HEADER_KEY: authorization

        # This runs the tests using Docker Compose, ensuring it builds the image and exits with the correct code based on test results
        # npm test exits with 0 → command exits with 0 → step passes ✅
        # npm test exits with 1 → command exits with 1 → step fails ❌
        run: |
          docker compose -f docker-compose.test.yml up backend-test \
            --build \
            --abort-on-container-exit \
            --exit-code-from backend-test 2>&1 | tee backend-test.log

      # Write test summary to job output
      - name: Backend Test Results summary
        if: always()
        run: |
          echo "## Backend test results" >> $GITHUB_STEP_SUMMARY
          echo "Full logs available in artifacts." >> $GITHUB_STEP_SUMMARY

        # Upload test logs to GitHub Actions Artifacts (stored for persistent data set to retain for 30 days)
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-logs-${{ github.run_id }}
          path: backend-test.log
          retention-days: 30

        # Cleanup containers and volumes after tests run, regardless of test success or failure
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
