# WORKFLOW FOR: Frontend Tests
# PURPOSE: Run frontend tests when called by other workflows or manually triggered
# TESTS: Runs frontend unit and integration tests isolated in a Docker container (focusing on component rendering, UI and API calls)

name: Test Frontend

on:
  workflow_call:
    # No secrets required as frontend doesn't need API keys

    # This outputs the outcome of the tests results to the workflow
    outputs:
      result:
        description: "Outcome of the frontend test job"
        value: ${{ jobs.test-frontend.outputs.result }}

  # Allow manual triggering for testing this workflow independently
  workflow_dispatch:

jobs:
  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.run-tests.outcome }}

    steps:
      # Downloads repo code to runner
      - name: Checkout code
        uses: actions/checkout@v4

        # Setup Docker Buildx for building and running test containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Run frontend tests in Docker container
      - name: Run Tests

        # This runs the tests using Docker Compose, ensuring it builds the image and exits with the correct code based on test results
        # npm test exits with 0 → command exits with 0 → step passes ✅
        # npm test exits with 1 → command exits with 1 → step fails ❌
        run: |
          docker compose -f docker-compose.test.yml up backend-test \
            --build \
            --abort-on-container-exit \
            --exit-code-from backend-test

        # Upload test logs to GitHub Actions Artifacts (stored for persistant data set to retain for 30 days)
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-logs-${{ github.run_id }}
          path: backend-test.log
          retention-days: 30

        # Cleanup containers and volumes after tests run, regardless of test success or failure
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
